---
- name: Executar Provisionamento de Banco via Stored Procedure
  hosts: all
  gather_facts: false
  become: yes
  collections:
    - community.general
  
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Chamada da Stored Procedure para a criação do banco
      debug:
        msg: "Chamando Stored Procedure para criação do banco para o cliente {{ nome_cliente }}"

    - name: Executar query SQL para criação do banco
      community.general.mssql_query:
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_password }}"
        login_host: "{{ inventory_hostname }}"
        db: "SLAB11"
        query: >
          EXEC prcontrole.dbo.cria_banco
          '{{ requisicao }}',
          '{{ ambiente }}',
          '{{ nome_cliente }}',
          '{{ nome_sistema }}',
          '{{ sufixo }}'
      register: result

    - name: Validar Execução
      debug:
        msg: "A Stored Procedure foi executada com sucesso para o cliente {{ nome_cliente }}."
      when: result.rowcount is defined