---
- name: Executar Provisionamento de Banco via Stored Procedure
  hosts: all
  gather_facts: false
  become: yes
  collections:
    - community.general
    - community.sql
    - microsoft.sql
  
  vars_files:
    - vars/vars.yml

  tasks:
    - name: SQL Server Stored Procedure para criação de banco
      microsoft.sql.server_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_hostname }}"
        db: "prcontrole"
        query: >
          EXEC prcontrole.dbo.cria_banco
          '{{ requisicao }}',
          '{{ ambiente }}',
          '{{ nome_cliente }}',
          '{{ nome_sistema }}',
          '{{ sufixo }}'
      register: result

    - name: Validar Execução
      debug:
        msg: "A Stored Procedure foi executada com sucesso para o cliente {{ nome_cliente }}."
      when: result.rowcount is defined