---
- name: Executar Provisionamento de Banco via Stored Procedure
  hosts: mssql_servers
  gather_facts: false
  
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Chamar Procedure de Criação de Banco
      community.general.mssql_query:
        login_user: "{{ db_admin_user }}"
        login_password: "{{ db_admin_password }}"
        login_host: "{{ inventory_hostname }}"
        db: "prcontrole"
        query: >
          EXEC prcontrole..cria_banco 
          '{{ requisicao }}', 
          '{{ ambiente }}', 
          '{{ nome_cliente }}', 
          '{{ nome_sistema }}', 
          '{{ sufixo }}'
      register: result

    - name: Validar Execução
      debug:
        msg: "A Procedure foi executada com sucesso para o cliente {{ nome_cliente }}."
      when: result.rowcount is defined