---
- name: Teste de Conexão MS SQL Server
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Valida a Conexão com o Banco de Dados
      ansible.builtin.command: >
        sqlcmd -S {{ db_mssql_hostname }} -U {{ db_mssql_user }} -P '{{ db_mssql_password }}'
        -C -t 5 -Q "SELECT 1"
      register: sql_output
      no_log: true # Protege a senha no log do AAP

    - name: Resultado do Teste
      ansible.builtin.debug:
        msg: "Conexão estabelecida com sucesso!"
      when: sql_output.rc == 0

    - name: Falha na Conexão
      ansible.builtin.fail:
        msg: "Erro ao conectar no SQL Server: {{ sql_output.stderr }}"
      when: sql_output.rc != 0
