---
- name: Testando Visibilidade da Collection Microsoft
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Listar bancos de dados (microsoft.sql)
      microsoft.sql.db_info:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_hostname }}"
      register: mssql_info

    - name: Debug Info
      ansible.builtin.debug:
        var: mssql_info