---
- name: Lista Banco de Dados Cadastrados
  hosts: localhost
  gather_facts: false
  become: yes
  
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Check MSSQL DB connection
      community.general.mssql_query:
        login_user: "{{ db_user }}"
        login_password: "{{ db_password }}"
        login_host: "{{ db_hostname }}"
        db: "prcontrole"
        script: "SELECT 1"
      register: result

    - name: Validar Execução
      debug:
        msg: "A query SQL foi executada com sucesso."
      when: result.rowcount is defined