---
- name: Capture Server Facts
  hosts: localhost

  tasks:
    - name: Collect only facts returned by facter
      ansible.builtin.setup:
        gather_subset:
        - 'all'
      register: setup

    - ansible.builtin.debug:
        var: setup