- name: Coletar informações de hosts do inventário
  hosts: localhost
  gather_facts: no
  tasks:
    - name: Listar informações de cada host
      debug:
        msg: |
          Informações do Host {{ item }}:
            - ID do Host: {{ hostvars[item]['foreman_id'] | default('Não disponível') }}
            - IPv4: {{ hostvars[item]['foreman_ipv4'] | default('Não disponível') }}
            - Localização: {{ hostvars[item]['foreman_location'] | default('Não disponível') }}
            - Organização: {{ hostvars[item]['foreman_organization'] | default('Não disponível') }}
            - Sistema Operacional: {{ hostvars[item]['foreman_facts']['os::name'] | default('Não disponível') }} {{ hostvars[item]['foreman_facts']['os::release::full'] | default('Não disponível') }}
            - SELinux Modo Atual: {{ hostvars[item]['foreman_facts']['os::selinux::current_mode'] | default('Não disponível') }}
      with_items: "{{ groups['all'] | difference(['localhost']) }}"