---
- name: Configuracao base o ambiente de UPDATEFIX
  hosts: localhost
  vars:
    ac_organization: SECURITY
    ac_cred_ac: CRED-AC-CONFIG
    ac_cred_servers: CRED-SSH-SERVER
    ac_inv_all_hosts: INV-ALL-HOSTS
    ac_inv_updatefix: INV-UPDATEFIX
    ac_proj_updatefix: PROJ-GIT-UPDATEFIX
    ac_hostname: aap01.aroque.com.br #alterar
  gather_facts: False
  tasks:

    - name: Criar inventory UPDATEFIX
      ansible.controller.inventory:
        name: "{{ ac_inv_updatefix }}"
        description: "Inventario de atualização de servidores"
        organization: "{{ ac_organization }}"
        state: present

    - name: Add Automation Controller no inventory de UPDATEFIX
      ansible.controller.host:
        name: "{{ ac_hostname }}"
        inventory: "{{ ac_inv_updatefix }}"

    - name: Add Grupo AC no inventory UPDATEFIX, add host de AC no grupo
      ansible.controller.group:
        name: AC
        inventory: "{{ ac_inv_updatefix }}"
#        preserve_existing_hosts: True
        hosts: "{{ ac_hostname }}"

    - name: Criar Job Template de UPFIX 1 - Acessibilidade e Inventários do UPDATEFIX
      ansible.controller.job_template:
        name: UPFIX 1 - ACCESS PREPARE
        job_type: "run"
        organization: "{{ ac_organization }}"
        inventory: "{{ ac_inv_all_hosts }}" # ele usa o inventory full como fonte da verdade
        project: "{{ ac_proj_updatefix }}"
        playbook: "upfix1/upfix1.yml"
        credentials:
          - "{{ ac_cred_ac }}"
        state: "present"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'upfix1_survey.json') }}"