- name: Coletar informações específicas do host
  hosts: localhost
  tasks:
    - name: Listar todos os hosts do inventário
      debug:
        msg: "{{ item }}"
      with_inventory_hostnames:
        - all

    - name: Listar hosts nos grupos específicos
      debug:
        msg: "Hosts no grupo {{ item }}: {{ groups[item] }}"
        loop:
        - INV-UPDATEFIX_0001
        - INV-UPDATEFIX_0001_FAIL
        - INV-UPDATEFIX_0001_OK

    - name: Definir variáveis com informações específicas do host
      set_fact:
        host_info: {
          "ID do Host": "{{ foreman_id }}",
          "IPv4": "{{ foreman_ipv4 }}",
          "Localização": "{{ foreman_location }}",
          "Organização": "{{ foreman_organization }}",
          "Sistema Operacional": "{{ foreman_facts['os::name'] }} {{ foreman_facts['os::release::full'] }}",
          "SELinux Modo Atual": "{{ foreman_facts['os::selinux::current_mode'] }}"
        }

    - name: Exibir informações coletadas
      debug:
        var: host_info