---
- name: Configuracao base o ambiente de UPDATEFIX
  hosts: localhost
  vars:
    ac_organization: SECURITY #SECURITY #alterar este item ############!!!!!!!!!!!!
    ac_cred_ac: CRED-AC-CONFIG
    ac_cred_servers: CRED-SSH-SERVER
    ac_inv_all_hosts: INV-ALL-HOSTS
    ac_inv_updatefix: INV-UPDATEFIX
    ac_proj_updatefix: PROJ-GIT-UPDATEFIX
    ac_hostname: localhost #alterar este item ##############!!!!!!!!!!!
  gather_facts: False
  tasks:

    - name: Create a workflow job template
      ansible.controller.workflow_job_template:
        name: UPDATEFIX - WORKFLOW
        description: Workflow UPDATEFIX
        organization: "{{ ac_organization }}"
        state: "present"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'upfix1_survey.json') }}"

    - name: Create a workflow job template 1
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 1 - PREPARAÇÃO
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 1 - PREPARAÇÃO
        organization: "{{ ac_organization }}"
 
    - name: Create a workflow job template 2
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 2_1 - ACESSO
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 2_1 - ACESSO
        organization: "{{ ac_organization }}"

    - name: Create a workflow job template 1
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 1 - PREPARAÇÃO
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 1 - PREPARAÇÃO
        organization: "{{ ac_organization }}"
          success_nodes:
          - UPFIX 2_1 - ACESSO

    - name: Create a workflow job template 3
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 2_2 - INVENTORY
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 2_2 - INVENTORY
        organization: "{{ ac_organization }}"

