---
- name: Configuracao base o ambiente de UPDATEFIX
  hosts: localhost
  vars:
    ac_organization: SECURITY #SECURITY #alterar este item ############!!!!!!!!!!!!
    ac_cred_ac: CRED-AC-CONFIG
    ac_cred_servers: CRED-SSH-SERVER
    ac_inv_all_hosts: INV-ALL-HOSTS
    ac_inv_updatefix: INV-UPDATEFIX
    ac_proj_updatefix: PROJ-GIT-UPDATEFIX
    ac_hostname: localhost #alterar este item ##############!!!!!!!!!!!
  gather_facts: False
  tasks:

    - name: Create a workflow job template
      awx.awx.workflow_job_template:
        name: UPDATEFIX - WORKFLOW
        description: Workflow UPDATEFIX
        organization: "{{ ac_organization }}"
        state: "present"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'upfix_version_survey.json') }}"

