---
- name: Configuracao base o ambiente de UPDATEFIX
  hosts: localhost
  vars:
    ac_organization: SECURITY #SECURITY #alterar este item ############!!!!!!!!!!!!
    ac_cred_ac: CRED-AC-CONFIG
    ac_cred_servers: CRED-SSH-SERVER
    ac_inv_all_hosts: INV-ALL-HOSTS
    ac_inv_updatefix: INV-UPDATEFIX
    ac_proj_updatefix: PROJ-GIT-UPDATEFIX
    ac_hostname: localhost #alterar este item ##############!!!!!!!!!!!
  gather_facts: False
  tasks:

    - name: Create a workflow job template
      ansible.controller.workflow_job_template:
        name: UPDATEFIX - WORKFLOW
        description: Workflow UPDATEFIX
        organization: "{{ ac_organization }}"
        state: "present"
        survey_enabled: yes
        survey_spec: "{{ lookup('file', 'upfix1_survey.json') }}"


    - name: Create a workflow job template 1
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 6_3 - REBOOT POS UPDATE
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 6_3 - REBOOT POS UPDATE
        organization: "{{ ac_organization }}"


    - name: Create a workflow job template 2
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 6_2 - UPDATE
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 6_2 - UPDATE
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 6_3 - REBOOT POS UPDATE

    - name: Create a workflow job template 3
      ansible.controller.workflow_job_template_node:
        identifier: UPFIX 6_1 - REBOOT TESTEE
        workflow: UPDATEFIX - WORKFLOW
        unified_job_template: UPFIX 6_1 - REBOOT TESTE
        organization: "{{ ac_organization }}"
        success_nodes:
          - UPFIX 6_2 - UPDATE
