---
- name: Verificações e Ações
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files: vars/vars.yml

  gather_facts: False
  tasks: 

#OBS: este teste de ping não é baseado no protocolo ICMP, este é o modulo ping do ansible que valida o acesso ao dispositivo
    - name: Verificar se os servidores existentes no inventario estão acessiveis para o Automation Controller
      ping:
      register: ping_result
      ignore_errors: True
      ignore_unreachable: true

    - name: test hosts
      debug:
        var: groups[updatefix_inventory_group_ok]

    - name: Ajustar variável de status do host no inventory e group Updatefix  {{ updatefix_inventory_group }} FAIL
      ansible.controller.host:
        name: "{{ item }}"
        inventory: "{{ updatefix_inventory }}"
        enabled: true
        variables:
          host_exists_in_inventory: "{{ host_exists_in_inventory }}" #definida na ultima automação
          hosts_reachable: FAIL
      loop: "{{ groups[updatefix_inventory_group_ok] }}"
      delegate_to: localhost

    - name: Ajustar variável de status do host no inventory e group Updatefix {{ updatefix_inventory_group }} OK
      ansible.controller.host:
        name: "{{ inventory_hostname }}"
        inventory: "{{ updatefix_inventory }}"
        enabled: true
        variables:
          host_exists_in_inventory: "{{ host_exists_in_inventory }}"
          hosts_reachable: "OK"
      when: ping_result.ping is defined and ping_result.ping == "pong"
      delegate_to: localhost

    - name: Ajustar variável de status do host no inventory e group Updatefix  {{ updatefix_inventory_group }} 
      ansible.controller.group:
        name: "{{ updatefix_inventory_group_ok }}"
        inventory: "{{ updatefix_inventory }}"
        hosts: "{{ inventory_hostname }}"
        preserve_existing_hosts: True
      when: ping_result.ping is defined and ping_result.ping == "pong"
      delegate_to: localhost

    - name: TEST
      ansible.controller.group:
        name: "{{ updatefix_inventory_group_ok }}"
        preserve_existing_hosts: False
        inventory: "{{ updatefix_inventory }}"
        hosts:
      loop: "{{ server_existing }}"
      
    - name: Add hosts no grupo com status OK Updatefix versão {{ updatefix_version }} no inventory UPDATEFIX
      ansible.controller.group:
        name: "{{ updatefix_inventory_group_ok }}"
        preserve_existing_hosts: True
        inventory: "{{ updatefix_inventory }}"
        hosts: "{{ item }}"
      loop: "{{ server_existing }}"
      when: host_exists_in_inventory == 'OK' and hosts_reachable == 'OK'
