---
- name: Construção de diretórios e logs para o UpdateFix
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  tasks:
    - name: Criar diretório de fatos do Ansible
      file:
        path: /etc/ansible/facts.d/
        state: directory
        mode: 0755
      when: ping_result.ping is defined and ping_result.ping == "pong"
      comment: "Cria um diretório para armazenar fatos do Ansible se o host estiver acessível."

    - name: Debug da variável controller_updatefix_inventory_group
      debug:
        var: controller_updatefix_inventory_group
      comment: "Exibe informações sobre o grupo de inventário UpdateFix."

    - name: Gerar diretórios de log do Ansible e UpdateFix
      file:
        state: directory
        path: "{{ item }}"
      loop:
        - /var/log/ansible
        - /var/log/ansible/updatefix
        - /var/log/ansible/updatefix/updatefix_{{ updatefix_version }}