---
- name: Capture Server Facts
  hosts: localhost
  gather_facts: False

  tasks:
    - name: Collect only facts returned by facts
      ansible.builtin.setup:
        gather_subset:
        - 'all'
      register: setup

    - ansible.builtin.debug:
        var: setup

