---
- name: Collect Facts from all Hosts
  hosts: all
  gather_facts: False

  tasks:
    - name: Collect only facts returned by facts
      ansible.builtin.setup:
        gather_subset:
        #- 'all'
        - '*system'
        - '*machine'
        - '*architecture'
      register: setup

    - ansible.builtin.debug:
        var: setup