---
- name: Collect Facts from all Hosts
  hosts: all
  gather_facts: False

  tasks:
    - name: Collect only facts returned by facts
      ansible.builtin.setup:
        gather_subset:
        - 'all'
      register: setup

    - ansible.builtin.debug:
        var: setup