---
- name: Collecting facts from all nodes
  hosts: all
  gather_facts: False

  tasks:
    - name: Collecting only facts returned by facts
      ansible.builtin.setup:
        #gather_subset:
        #- 'all'
        filter:
        - '*system'
        - '*machine'
        - '*architecture'
      register: setup

    - ansible.builtin.debug:
        var: setup