---
- name: Validate DB2 database instances
  hosts: all
  become: "{{ os_username }}"
  vars_files:
    - vars/vars.yml

  tasks:
    - name: Validate DB2 database with {{ os_username }} user
      command: 
        - db2 list db directory
        - db2 connect to {{ db2_db_name }} user {{ db_co_user }}
      register: db2_db_check_instance
      ignore_errors: true

    - name: Display validation result
      debug:
        msg: "DB2 database with {{ os_username }} user {{ 'succeeded' if db2_db_check_instance.rc == 0 else 'failed' }}"
