---
- name: Rollback DB2 database instances
  hosts: all
  become: "{{ os_username }}"
  vars_files:
    - vars/vars.yml

  tasks:
    # DB2 Database Information for the Rollback process
    - name: Get DB2 Node-Name directory with {{ os_username }} user
      command: 
        - db2 list node directory | grep 'Node name' | awk -F' ' '{ print $4 }'
        - db2 list db directory | grep 'Database name' | awk -F' ' '{ print $4 }'
        - db2 list node directory | grep 'Hostname' | awk -F' ' '{ print $3 }'
        - db2 list node directory | grep 'Service name' | awk -F' ' '{ print $4 }'
        - db2level | grep 'Product is installed at' | awk '{ print $5 }' | awk -F'"' '{ print $2 }'
      register: db2_db_inform
      ignore_errors: true

    # DB2 Drop OLD Instance
    - name: Drop DB2 New instance with ROOT user
      become: True
      command: "{{ db2_db_inform[5] }}/instance/db2idrop db2sec"
      register: db2_db_drop
      ignore_errors: true

    # DB2 Create Instance into the Old Directory
    - name: Create DB2 OLD instance with ROOT user
      become: True
      command: "{{ db2_db_path }}/instance/db2icrt -u db2sec db2sec"
      register: db2_db_create
      ignore_errors: true

    # DB2 Instance Catalog
    - name: Catalog DB2 Instance Node and DB
      become: "{{ os_username }}"
      command:
        - db2 catalog tcpip node {{ db2_db_inform[1] }} remote {{ db2_db_inform[3] }} server {{ db2_db_inform[4] }}
        - db2 catalog database {{ db2_db_inform[2] }} at node {{ db2_db_inform[1] }}
      register: db2_instance_catalog
      ignore_errors: true

    - name: Display validation result
      debug: 
        var: db2_instance_catalog
