---
- name: RoadMap
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: True
  become: yes
  tasks:

    - name: Test de reboot
      debug:
        msg: "Test de reboot"
      