---
- name: RoadMap de Atualização
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: True
  become: yes
  tasks:

    - name: Capturar a última versão do histórico do YUM
      shell: yum history | awk 'NR==4 {print $1}'
      register: yum_history_id

    - name: Armazenar o número do histórico do YUM
      template:
        src: yum_history_fact.j2
        dest: "/etc/ansible/facts.d/yum_history.fact"    

    - block:
        - name: Update all packages (all)
          yum:
            name: '*'
            state: latest
            exclude: java*,mysql*,postgresql*,nginx*,httpd*,php*,oracle*,sap*,jboss*,weblogic*
          register: register_update
          when: update_type == 'all'

        - name: Update bugfix packages (bugfix)
          yum:
            name: '*'
            state: latest
            bugfix: true
          register: register_update
          when: update_type == 'bugfix'

        - name: Update security packages (security)
          yum:
            name: '*'
            state: latest
            security: true
          register: register_update
          when: update_type == 'security'

        - name: Reboot server after package update
          reboot:
          when: server_reboot == 'yes'

      rescue:
        - name: Adicionar mensagem de erro de log
          lineinfile:
            path: /var/log/ansible/updatefix/updatefix_{{ updatefix_version }}.log
            line: |
              "################# STATUS DO UPDATE ##########################"
              {{ lookup('pipe','date +%Y-%m-%d') }} {{ lookup('pipe','date +%H:%M:%S') }} {{ inventory_hostname }}: Identificamos uma falha durante o processo de update
              {{ lookup('pipe','date +%Y-%m-%d') }} {{ lookup('pipe','date +%H:%M:%S') }} {{ inventory_hostname }}: Log de erro do processo de update:
              {{ register_update.stdout | default('N/A') }}

  handlers:
    - name: Log Success Update
      lineinfile:
        path: /var/log/ansible/updatefix/updatefix_{{ updatefix_version }}.log
        line: |
          "################# STATUS DO UPDATE ##########################"
          UPDATE REALIZADO COM SUCESSO
          {{ lookup('pipe','date +%Y-%m-%d') }} {{ lookup('pipe','date +%H:%M:%S') }} {{ inventory_hostname }}: Detalhes do processo:
          {{ register_update.stdout | default('N/A') }}
