---
- name: Seleção de hosts e ajustes de inventarios
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  tasks:

    - name: Coletar fatos locais
      ansible.builtin.setup:
        filter: ansible_local

    - name: informacao local facts
      debug:
        var: ansible_facts.ansible_local