---
- name: Validação de subscrição - UPFIX 3.3 - Mount Point
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  become: yes
  
  tasks:
    - name: Executar findmnt --verify
      ansible.builtin.command:
        cmd: findmnt --verify
      register: findmnt_result
      ignore_errors: yes

#necessário pkgs util-linux-core findmnt

    - name: Definir mount_points_fstab_check com base no resultado
      set_fact:
        mount_points_fstab_check: "{{ 'OK' if findmnt_result.rc == 0 else 'FAIL' }}"
        mount_points_fstab_stdout: "{{ findmnt_result.stdout }}"

    - name: Exibir o resultado da verificação
      debug:
        var: mount_points_fstab_check

#ajustar uma variavel fstab e outra mountpoint 
#findmnt -nr --nofsroot --noheadings --output TARGET | grep -vE '^/(proc|sys|dev|run)'
#findmnt -nr --real --nofsroot --noheadings --output TARGET

#######
########## validar dispositivos montados que não fazem parte do fstab
######
    - name: Coletar pontos de montagem atuais
      shell: findmnt -nr --nofsroot --noheadings --output TARGET | grep -vE '^/(proc|sys|dev|run)'
      register: current_mount_points

    - name: Ler /etc/fstab
      slurp:
        src: /etc/fstab
      register: fstab_content

    - name: Decodificar conteúdo do fstab
      set_fact:
        fstab_decoded: "{{ (fstab_content['content'] | b64decode).split('\n') }}"

    - name: Processar e comparar pontos de montagem
      set_fact:
        mount_points_stdout: "{{ current_mount_points.stdout_lines | difference(fstab_decoded | map('regex_replace', '^(\\S+)\\s+(\\S+).*$', '\\2') | list ) }}"

    - name: Definir variável de status do ponto de montagem
      set_fact:
        mount_points_check: "{{ 'OK' if mount_points_stdout | length == 0 else 'WARNING' }}"

    - name: Exibir pontos de montagem não listados no fstab
      debug:
        msg: "Ponto de montagem não listado no fstab: {{ item }}"
      loop: "{{ mount_points_stdout }}"
      when: mount_points_stdout | length > 0

####Configuracao de facts
    - name: Criar arquivos de facts para mount_points_check
      template:
        src: mount_points_check.j2
        dest: "/etc/ansible/facts.d/mount_points_check.fact"