---
- name: Validação de subscrição - UPFIX 3.10 -  process
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  become: yes
  tasks:
    - name: Obter os 10 principais processos por uso de memória
      ansible.builtin.shell: "ps aux --sort=-%mem | head -n 11 | awk '{print $1, $11}'"
      register: top_processes_raw

    - name: Definir a variável top_processes
      set_fact:
        top_processes: "{{ top_processes_raw.stdout_lines }}"

    - name: Obter os 10 principais processos não-root por uso de memória
      ansible.builtin.shell: "ps aux --sort=-%mem | grep -v '^root' | head -n 11 | awk '{print $1, $11}'"
      register: top_non_root_processes_raw

    - name: Definir a variável top_non_root_processes
      set_fact:
        top_non_root_processes: "{{ top_non_root_processes_raw.stdout_lines }}"

    - name: Exibir os 10 principais processos
      ansible.builtin.debug:
        var: top_processes

    - name: Exibir os 10 principais processos não-root
      ansible.builtin.debug:
        var: top_non_root_processes

    - name: Criar arquivos de facts para proccess_status_check
      template:
        src: proccess_status_check.j2
        dest: "/etc/ansible/facts.d/proccess_status_check.fact"