---
- name: Validação de subscrição - UPFIX 3.3 - Mount Point
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  become: yes
  
  tasks:
    - name: Executar findmnt --verify
      ansible.builtin.command:
        cmd: findmnt --verify
      register: findmnt_result
      ignore_errors: yes

#necessário pkgs util-linux-core findmnt

    - name: Definir mount_points_check com base no resultado
      set_fact:
        mount_points_check: "{{ 'OK' if findmnt_result.rc == 0 else 'FAIL' }}"
        mount_points_stdout: "{{ findmnt_result.stdout }}"

    - name: Exibir o resultado da verificação
      debug:
        var: mount_points_check

    - name: Criar arquivos de facts para mount_points_check
      template:
        src: mount_points_check.j2
        dest: "/etc/ansible/facts.d/mount_points_check.fact"
#######
########## validar dispositivos montados que não fazem parte do fstab
######
    - name: Coletar informações de pontos de montagem com findmnt
      ansible.builtin.command: findmnt -rn
      register: findmnt_output

    - name: Ler conteúdo do fstab
      ansible.builtin.slurp:
        src: /etc/fstab
      register: fstab_content

    - name: Converter conteúdo do fstab para texto
      ansible.builtin.set_fact:
        fstab_text: "{{ fstab_content['content'] | b64decode }}"

    - name: Encontrar pontos de montagem não listados no fstab
      ansible.builtin.set_fact:
        unlisted_mount_points: "{{ findmnt_output.stdout_lines | map('regex_replace', ' .*', '') | difference(fstab_text | regex_findall('/dev/[\\w/]+')) }}"

    - name: Exibir pontos de montagem não listados no fstab
      ansible.builtin.debug:
        var: unlisted_mount_points
