---
- name: Validação de subscrição - UPFIX 3.3 - Mount Point
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  become: yes
  
  tasks:
    - name: Executar findmnt --verify
      ansible.builtin.command:
        cmd: findmnt --verify
      register: findmnt_result
      ignore_errors: yes

#necessário pkgs util-linux-core findmnt

    - name: Definir mount_points_check com base no resultado
      set_fact:
        mount_points_check: "{{ 'OK' if findmnt_result.rc == 0 else 'FAIL' }}"
        mount_points_stdout: "{{ findmnt_result.stdout }}"

    - name: Exibir o resultado da verificação
      debug:
        var: mount_points_check

    - name: Criar arquivos de facts para mount_points_check
      template:
        src: mount_points_check.j2
        dest: "/etc/ansible/facts.d/mount_points_check.fact"
#######
########## validar dispositivos montados que não fazem parte do fstab
######
    - name: Obter pontos de montagem atuais
      ansible.builtin.command: findmnt --real --nofsroot --noheadings --output TARGET
      register: mounted_points

    - name: Obter pontos de montagem do fstab
      ansible.builtin.command: awk '$1!~/^#/ && $1!~/^none/ {print $2}' /etc/fstab
      register: fstab_points

    - name: Comparar pontos de montagem com fstab
      ansible.builtin.command: echo "{{ item }}"
      loop: "{{ mounted_points.stdout_lines }}"
      when: item not in fstab_points.stdout_lines
      register: unlisted_mount_points

    - name: Exibir pontos de montagem não listados no fstab
      ansible.builtin.debug:
        var: unlisted_mount_points.results
