---
- name: Listar pontos de montagem do servidor - UPFIX 3.1 - FileSystem
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  
  tasks:
    - name: Coletar fatos do sistema
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'mounts'

    - name: Exibir pontos de montagem
      debug:
        var: ansible_mounts