---
- name: Validação de subscrição - UPFIX 3.4 - Subscription
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  tasks:
    - name: Verificar repositórios existentes
      ansible.builtin.command:
        cmd: yum repolist
      register: repolist_result
      ignore_errors: yes

    - name: Definir repository_check com base no resultado
      set_fact:
        repository_check: "{{ 'OK' if 'repolist' in repolist_result.stdout else 'FAIL' }}"

    - name: Exibir o resultado da verificação
      debug:
        var: repository_check

    - name: Criar arquivos de facts para repository_check
      template:
        src: repository_check.j2
        dest: "/etc/ansible/facts.d/repository_check.fact"