---
- name: Validação de subscrição - UPFIX 3.4 - Subscription
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  tasks:
    - name: Executar findmnt --verify
      ansible.builtin.command:
        cmd: findmnt --verify
      register: findmnt_result
      ignore_errors: yes

    - name: Definir mount_points_check com base no resultado
      set_fact:
        mount_points_check: "{{ 'OK' if findmnt_result.rc == 0 else 'FAIL' }}"

    - name: Exibir o resultado da verificação
      debug:
        var: mount_points_check

    - name: Criar arquivos de facts para mount_points_check
      template:
        src: mount_points_check.j2
        dest: "/etc/ansible/facts.d/mount_points_check.fact"