---
- name: Listar pontos de montagem do servidor - UPFIX 3.2 - FileSystem somente leitura
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False

  tasks:
    - name: Coletar fatos do sistema
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'mounts'

    - name: Verificar se / está em modo somente leitura
      set_fact:
        root_readonly_check: "FAIL"
      when: "'ro' in (item.options|default('')) and item.mount == '/'"
      loop: "{{ ansible_mounts }}"
#      no_log: False

    - name: Verificar se /boot está em modo somente leitura
      set_fact:
        boot_readonly_check: "FAIL"
      when: "'ro' in (item.options|default('')) and item.mount == '/boot'"
      loop: "{{ ansible_mounts }}"
#     no_log: False

    - name: Definir root_readonly_check como OK se não definido
      set_fact:
        root_readonly_check: "OK"
      when: root_readonly_check is not defined

    - name: Definir boot_readonly_check como OK se não definido
      set_fact:
        boot_readonly_check: "OK"
      when: boot_readonly_check is not defined

    - name: Definir as opções de montagem para root
      set_fact:
        root_options_check: "{{ item.options }}"
      loop: "{{ ansible_mounts }}"
      when: item.mount == '/'

    - name: Definir as opções de montagem para boot
      set_fact:
        boot_options_check: "{{ item.options }}"
      loop: "{{ ansible_mounts }}"
      when: item.mount == '/boot'

    - name: Criar arquivos de facts para root_readonly_check
      template:
        src: root_readonly_check.j2
        dest: "/etc/ansible/facts.d/root_space_check.fact"

    - name: Criar arquivos de facts para boot_space_check
      template:
        src: boot_readonly_check.j2
        dest: "/etc/ansible/facts.d/boot_readonly_check.fact"
