---
- name: Validação de subscrição - UPFIX 3.4 - Subscription
  hosts: "{{ updatefix_inventory_group_ok }}"
  vars_files:
    - vars/vars.yml
  gather_facts: False
  tasks:
    - name: Coletar fatos do sistema
      ansible.builtin.setup:
        gather_subset:
          - '!all'
          - 'mounts'

    - name: Ler conteúdo do /etc/fstab
      ansible.builtin.slurp:
        src: /etc/fstab
      register: fstab_content

    - name: Decodificar conteúdo do fstab
      set_fact:
        fstab_lines: "{{ (fstab_content['content'] | b64decode).split('\n') }}"

    - name: Verificar se as montagens do fstab estão ativas
      vars:
        active_mounts: "{{ ansible_mounts | map(attribute='mount') | list }}"
      debug:
        msg: "{{ item.split()[1] }} está montado"
      when:
        - item.split() | length > 1
        - item.split()[0] != "#"
        - "'/' in item.split()[1]"
        - item.split()[1] in active_mounts
      loop: "{{ fstab_lines }}"
      loop_control:
        label: "{{ (item.split() | default(['','']))[1] }}"


    - name: Verificar se as montagens do fstab estão ativas
      vars:
        active_mounts: "{{ ansible_mounts | map(attribute='mount') | list }}"
      debug:
        msg: "{{ item.split()[1] }} está montado"
      when:
        - item.split() | length > 1
        - item.split()[0] != "#"
        - item.split()[1] in active_mounts
      loop: "{{ fstab_lines }}"
      loop_control:
        label: "{{ (item.split() | default(['','']))[1] }}"